# Generated by Django 3.1.3 on 2020-12-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Free', 'free'), ('Beginner', 'beg'), ('Professional', 'pro')], default='Free', max_length=40),
        ),
    ]
