# Generated by Django 3.1.3 on 2020-12-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0029_auto_20201208_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orginal_cart',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
