# Generated by Django 3.1.3 on 2020-12-10 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0030_auto_20201210_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orginal_cart',
            new_name='original_cart',
        ),
    ]
