# Generated by Django 3.1.3 on 2020-12-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fitness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme_name', models.CharField(max_length=100, null=True)),
                ('week', models.DecimalField(decimal_places=0, max_digits=2, null=True)),
                ('day', models.DecimalField(decimal_places=0, max_digits=2, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Fitness',
                'ordering': ('day',),
            },
        ),
    ]
