# Generated by Django 3.1.3 on 2020-12-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitness',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='fitness',
            name='image_url',
        ),
        migrations.AddField(
            model_name='fitness',
            name='body_type',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='fitness',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fitness',
            name='video_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
