# Generated by Django 3.1.3 on 2020-12-27 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programme',
            old_name='image_file',
            new_name='image',
        ),
    ]
