# Generated by Django 3.1.3 on 2020-12-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20201227_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='description',
            field=models.TextField(max_length=400),
        ),
    ]
