# Generated by Django 3.1.3 on 2020-12-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme_name', models.CharField(max_length=100, null=True)),
                ('week', models.DecimalField(decimal_places=0, max_digits=2, null=True)),
                ('day_1', models.TextField(max_length=1000, null=True)),
                ('day_2', models.TextField(max_length=1000, null=True)),
                ('day_3', models.TextField(max_length=1000, null=True)),
                ('day_4', models.TextField(max_length=1000, null=True)),
                ('day_5', models.TextField(max_length=1000, null=True)),
                ('day_6', models.TextField(max_length=1000, null=True)),
                ('day_7', models.TextField(max_length=1000, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Lesson',
            },
        ),
    ]
